#!/bin/sh

USER='hugo'

if [ ! -n "$SOURCE" ]; then SOURCE="/app/project/"; fi
if [ ! -n "$BUILD" ]; then BUILD="/app/build/"; fi


function serve() {
    suexec $USER hugo server -p 8080 --bind 0.0.0.0 $SOURCE
}

function build() {
    suexec $USER hugo
}

function hugo() {
    suexec $USER $@
}

function sudo() {
    suexec $USER $@
}

case "$1" in
    serve) serve ;;
    build) build ;;
    hugo) hugo $@ ;;
    sudo) sudo $@ ;;
    *) exec "$@" ;;
esac
