#!/bin/bash
set -e

if $[ ! -d "/data/configdb" ]; then mkdir -p /data/configdb; fi
if $[ ! -d "/data/db" ]; then mkdir -p /data/db; fi
 
if [ "${1:0:1}" = '-' ]; then
    set -- mongod "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then
    chown -R mongodb /data/configdb /data/db
    exec "suexec" mongodb "$BASH_SOURCE" "$@"
fi

if [ "$1" = 'mongod' ]; then
    numa='numactl --interleave=all'
    if $numa true &> /dev/null; then
        set -- $numa "$@"
    fi
fi

exec "$@"
